server:
  port: 8080


---
spring:
  datasource:
    url: 'jdbc:mysql://byerline.me:3306/bikes'
    username: 'root'
    password: 'adiumDB'
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  thymeleaf:
    enabled: true

