server:
  port: 8080

---
spring:
  datasource:
    url: 
    username: 
    password: 
    driver-class-name:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

