openapi: 3.0.0
info:
  description: Business management system for SoCal Electro Bike (SCEB) Company
  version: '1.0.0'
  title: SoCal Electro Bike API
tags:
  - name: Employee
    description: Functions that employees can perform
  - name: Manager
    description: Functions that managers can perform
  - name: Owner
    description: Functions that owners can perform
  - name: Bookkeeper
    description: Functions that bookkeepers can perform
paths:
  '/login':
    post:
      tags:
        - Employee
        - Manager
        - Owner
        - Bookkeeper
      summary: Lets user login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: 'account2145'
                password:
                  type: string
                  example: 't$V#$Trtu4R#'
      responses:
        '201':
          description: |
            OK
            User successfully logged in.
        '401':
          description: |
            Unauthorized
            Incorrect username or password.
  '/inventory/search':
    post:
      tags:
        - Employee
        - Manager
        - Owner
      summary: Allows user to search for an item in inventory
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              required:
                - bikeColor
                - priceMin
                - priceMax
                - inStock
                - condition
                - make
              properties:
                bikeColor:
                  type: string
                  example: blue
                priceMin:
                  type: number
                  example: 100.50
                priceMax:
                  type: number
                  example: 250
                inStock:
                  type: boolean
                  example: true
                condition:
                  type: string
                  example: used
                make:
                  type: string
                  example: hongda
      responses:
        '200':
          description: |
            OK
            Returns a list of bikes.
          content:
            application/json:
              example:
                - bikeId: 1423786
                  make: Hongda
                  model: M125
                  color: red
                  cost: 399
                  description: bike description
                  condition: used
                - bikeId: 89763288
                  make: Suzuccki
                  model: X613
                  color: pink
                  cost: 549
                  description: other description
                  condition: new
  '/inventory/addProduct/{status}':
    post:
      tags:
        - Employee
        - Manager
        - Owner
      summary: Lets the user add planned/actual product to database with their ID
      parameters:
        - name: status
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              required:
                - addStatus
                - GUID
              properties:
                addStatus:
                  type: string
                  example: 'planned'
                GUID:
                  type: string
                  example: 'c894jv72'
      responses:
        '201':
          description: Item has been added to database.
  '/inventory/updateProduct/{productId}':
    put:
      tags:
        - Employee
        - Manager
        - Owner
      summary: Updates a product's status attached with employee ID
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
                - GUID
              properties:
                status:
                  type: string
                  example: 'sold'
                GUID:
                  type: string
                  example: 'c894jv72'
      responses:
        '201':
          description: Item's status has been updated
  '/sales/{timePeriod}':
    get:
      tags:
        - Employee
        - Manager
        - Owner
      summary: Generates statistical summary report of inventory for a specified week, month or year
      parameters:
        - name: timePeriod
          in: path
          required: true
          schema:
            type: array
            items:
              type: string
              enum:
                - "DD/MM/YYYY"
                - "DD/MM/YYYY"
      responses:
        '200':
          description: |
            OK
            // TODO
  '/order/status/{orderId}':
    get:
      tags:
        - Employee
        - Manager
        - Owner
      summary: Lets the user search for item in inventory.
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: |
            OK
            Returns a list of CDO Analytics Tools or an empty list if none exist.
          content:
            application/json:
              example:
                username: 'employee123'
                password: 'eF#12tT$@%^Ywe'
  '/order/setStatus/{orderId}':
    post:
      tags:
        - Employee
        - Manager
        - Owner
      summary: Changes the status on specified order number
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Order status has been updated.
  '/shiftChart':
    get:
      tags:
        - Employee
      summary: Lets employee view shift chart.
      responses:
        '200':
          description: |
            OK
            // TODO
  '/account/{GUID}/changePassword':
    patch:
      tags:
        - Employee
      summary: Allows the user to enter current and new password
      parameters:
        - name: GUID
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/jason:
            schema:
              type: object
              required:
                - currentPassword
                - newPassword
              properties:
                currentPassword:
                  type: string
                  example: 'gerth@67gg9tt'
                newPassword:
                  type: string
                  example: 'c893g4j%^&v72'
      responses:
        '200':
          description: Password has been updated.
  '/account/{GUID}/changeEmail':
    patch:
      tags:
        - Employee
      summary: Allows the user to enter current and new email
      parameters:
        - name: GUID
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - currentEmail
                - newEmail
              properties:
                currentEmail:
                  type: string
                  example: 'vevergarden2@sdsu.edu'
                newEmail:
                  type: string
                  example: 'violet.evergarden@sdsu.edu'
      responses:
        '200':
          description: Email has been updated.
  '/account/{GUID}/timeSheet':
    post:
      tags:
        - Employee
      summary: Records time in and out of an employee.
      parameters:
        - name: GUID
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                timeIn:
                  type: string #TODO
                timeOut:
                  type: string #TODO
      responses:
        '200':
          description: Time is recorded.
        '400':
          description: Invalid input.
  '/account/{GUID}/requests':
    post:
      tags:
        - Employee
      summary: Lets employee request for Sick Days/Holidays/PTO
      parameters:
        - name: GUID
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - requestMessage
              properties:
                requestMessage:
                  type: string
                  example: 'Dear Ms. Manager, ...'
      responses:
        '200':
          description: Request message has been sent.