openapi: 3.0.0
info:
  description: Business management system for SoCal Electro Bike (SCEB) Company
  version: '1.0.0'
  title: SoCal Electro Bike API
tags:
  - name: Account
    description: Functions related to account
  - name: Inventory
    description: Functions related inventory management
  - name: Sales Reports
    description: Functions related to sakes reports
  - name: Retail Orders
    description: Functions related retail orders management
  - name: Repair Orders
    description: Functions related repair ticket system
  - name: Employee Management
    description: Functions related employee management
  - name: Help Function
    description: Generates and delivers FAQ's
paths:
  '/login':
    post:
      tags:
        - Account
      summary: Lets user login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: 'account2145'
                password:
                  type: string
                  example: 't$V#$Trtu4R#'
      responses:
        '201':
          description: |
            OK
            User successfully logged in.
        '401':
          description: |
            Unauthorized
            Incorrect username or password.
  '/account/changePassword':
    patch:
      tags:
        - Account
      summary: Allows the user to enter current and new password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - currentPassword
                - newPassword
              properties:
                currentPassword:
                  type: string
                  example: 'gerth@67gg9tt'
                newPassword:
                  type: string
                  example: 'c893g4j%^&v72'
      responses:
        '200':
          description: Password has been updated.
  '/account/changeEmail':
    patch:
      tags:
        - Account
      summary: Allows the user to enter current and new email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - currentEmail
                - newEmail
              properties:
                currentEmail:
                  type: string
                  example: 'vevergarden2@sdsu.edu'
                newEmail:
                  type: string
                  example: 'violet.evergarden@sdsu.edu'
      responses:
        '200':
          description: Email has been updated.
  '/account/timeSheet':
    post:
      tags:
        - Account
      summary: Records time in and out of an employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  example: 'MM/DD/YYYY'
                timeIn:
                  type: string
                  example: 'HH/MM'
                timeOut:
                  type: string
                  example: 'HH/MM'
      responses:
        '200':
          description: Time is recorded.
        '400':
          description: Invalid input.
  '/account/shiftChart':
    post:
      tags:
        - Account
      summary: Display an employee's shift chart
      responses:
        '200':
          description: |
            OK
            Returns the employee's work schedule
          content:
            application/json:
              example:
                daysOfWork: '1,2,3,4,5,6,7' #1:Mon,2:Tue...7:Sun
                startWorkHours: '8,8,8,8,8,NULL,NULL'
                endWorkHours: '4,3,4,3,4,NULL,NULL'
                totalWeeklyHours: '38'

  '/account/timeOffRequests':
    post:
      tags:
        - Account
      summary: Lets employee request for Sick Days/Holidays/PTO
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - requestMessage
                - employeeID
              properties:
                employeeID:
                  type: integer
                  example: 1
                timePeriod:
                  type: string
                  example: '12/20/2020 - 01/02/2021'
                requestMessage:
                  type: string
                  example: 'Dear Ms. Manager, ...'

      responses:
        '200':
          description: Successfully Received

  '/inventory/search':
    post:
      tags:
        - Inventory
      summary: Allows user to search for an item in inventory
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              required:
                - bikeColor
                - priceMin
                - priceMax
                - inStock
                - condition
                - make
              properties:
                bikeColor:
                  type: string
                  example: blue
                priceMin:
                  type: number
                  example: 100.50
                priceMax:
                  type: number
                  example: 250
                inStock:
                  type: boolean
                  example: true
                condition:
                  type: string
                  example: used
                make:
                  type: string
                  example: hongda
      responses:
        '200':
          description: |
            OK
            Returns a list of bikes.
          content:
            application/json:
              example:
                - bikeId: 1423786
                  make: Hongda
                  model: M125
                  color: red
                  cost: 399
                  description: bike description
                  condition: used
                - bikeId: 89763288
                  make: Suzuccki
                  model: X613
                  color: pink
                  cost: 549
                  description: other description
                  condition: new
  '/inventory/addProduct':
    post:
      tags:
        - Inventory
      summary: Lets the user add planned/actual product to database with their ID
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              required:
                - addStatus
                - GUID
              properties:
                bikeDisplayName:
                  type: string
                  example: Coolbike3000
                addedBy:
                  type: string
                  example: Jacob
                make:
                  type: string
                  example: Trek
                model:
                  type: string
                  example: Fast
                color:
                  type: string
                  example: Blue
                wholesaleCost:
                  type: number
                  example: 120.03
                retailCost:
                  type: number
                  example: 175.99
                description:
                  type: string
                  example: This bike goes fast
                condition:
                  type: string
                  example: New
                quantity:
                  type: integer
                  example: 47
      responses:
        '201':
          description: Item has been added to database
  '/order/create':
    post:
      tags:
        - Retail Orders
      summary: Changes the status on specified order number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - customerName
                - customerAddress
                - isPaid
                - paymentMethod
              properties:
                customerName:
                  type: string
                  example: 'Gertrude Parker'
                customerAddress:
                  type: string
                  example: '123 abc dr. San Diego, Ca 91009'
                isPaid:
                  type: boolean
                  example: true
                paymentMethod:
                  type: string
                  example: 'card'
                itemIds:
                  type: array
                  items:
                    type: integer
                  example: [900033, 100020, 367289]
      responses:
        '200':
          description: Order has been created.
  '/order/status/{orderId}':
    get:
      tags:
        - Retail Orders
      summary: Lets the user search for an order.
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: |
            OK
            Returns an order's information and status.
          content:
            application/json:
              example:
                status: 'processing'
                customerName: 'Alex Ha'
                customerAddress: '123 jonbdf drive, san diego, ca 92123'
                totalCost: '$519'
                deliveryMethod: 'express'
                estimatedArrival: '10/28/2020'

        '404':
          description: 'Order not found.'
  '/order/status/set/{orderId}/{status}':
    get:
      tags:
        - Retail Orders
      summary: Changes the status on specified order number
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: number
        - name: status
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order status has been updated.
  '/salesReport':
    post:
      tags:
        - Sales Reports
      summary: Generates summary report of inventory for a specified week, month or year
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - companyId
                - timePeriod
              properties:
                timePeriod:
                  type: string
                  example: 'DD/MM/YYYY-DD/MM/YYYY'
      responses:
        '200':
          description: |
            OK
          content:
            application/json:
              example:
                numberOfItemsReturned: '4'
                numberOfItemsReturnedDefective: '67'
                numberOfItemsReturnedExcess: '440'
                numberOfItemsSoldInStore: '12289'
                numberOfItemsShipped: '56'
                numberOfItemsRepaired: '87'
  '/manager/addEmployee':
    post:
      tags:
        - Employee Management
      summary: Lets a manager add a new employee account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
              properties:
                employeeName:
                  type: string
                  example: 'Jacob Byerline'
                address:
                  type: string
                  example: '123 Happy St. La Mesa, Ca 91942'
                social:
                  type: integer
                  example: 867530912
                position:
                  type: string
                  example: 'Owner'
                payRate:
                  type: number
                  example: 420.69
                payrollType:
                  type: number
                  example: 'Hourly'
                privilegeLevel:
                  type: string
                  example: 'ADMIN'
                username:
                  type: string
                  example: 'jbyerline'
                password:
                  type: string
                  example: 'password'
      responses:
        '200':
          description: 'New employee account created.'
  '/manager/updateEmployee':
    patch:
      tags:
        - Employee Management
      summary: Lets the manager to update an employee's account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - positionTitle
              properties:
                employeeId:
                  type: integer
                  example: '239'
                employeeName:
                  type: string
                  example: 'Jacob Byerline'
                address:
                  type: string
                  example: '123 Happy St. La Mesa, Ca 91942'
                social:
                  type: integer
                  example: 867530912
                position:
                  type: string
                  example: 'Owner'
                payRate:
                  type: number
                  example: 420.69
                payrollType:
                  type: number
                  example: 'Hourly'
                privilegeLevel:
                  type: string
                  example: 'ADMIN'
                username:
                  type: string
                  example: 'jbyerline'
                password:
                  type: string
                  example: 'password'
      responses:
        '200':
          description: Employee's account has been updated
  '/manager/removeEmployee':
    patch:
      tags:
        - Employee Management
      summary: Lets a manager remove an employee account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                employeeId:
                  type: integer
                  example: '239'
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "User not found"
  '/repair/createOrder':
    post:
      tags:
        - Repair Orders
      summary: Creates a repair order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                customerName:
                  type: string
                  example: 'Marie Duffy'
                customerAddress:
                  type: string
                  example: '2973 Aztec Dr. San Diego, Ca 11192'
                customerEmail:
                  type: string
                  example: 'MarieDuffy@DuffBeer.net'
                customerPhone:
                  type: string
                  example: '(619)420-6969'
                description:
                  type: string
                  example: 'My bike dont work... halp'
                make:
                  type: string
                  example: 'Amazon Basics'
                model:
                  type: string
                  example: 'Slow :('
                additionalComments:
                  type: string
                  example: 'I need my bike back soon plz'
      responses:
        "200":
          description: "success"
  '/repair/setOrderStatus':
    post:
      tags:
        - Repair Orders
      summary: Set repair order status
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                orderId:
                  type: integer
                  example: 432
                status:
                  type: string
                  example: 'Repair In Progress'

      responses:
        "200":
          description: "success"
  '/repair/getOrderStatus/{orderId}':
    get:
      tags:
        - Repair Orders
      summary: Set repair order status
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: number

      responses:
        "200":
          description: |
            OK
          content:
            application/json:
              example:
                orderStatus: 'Completed'
